# Generated by Django 4.2.3 on 2024-08-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='profile_images/')),
                ('bio', models.TextField(blank=True)),
                ('social_media', models.JSONField(blank=True)),
            ],
        ),
    ]
