# Generated by Django 4.2.3 on 2024-08-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_alter_profile_social_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='link',
            name='visit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
